
import csv

# Defining the meal data
meals = [
    # Breakfast
    {"meal_type": "Breakfast", "meal_name": "Mandazi", "preparation_time": "Moderate", "calories": "High in Calories",
     "ingredients": "Rich in carbs", "recipe_link": "https://swahilifood.com/how-to-make-soft-mandazi-biegnets/"},
    {"meal_type": "Breakfast", "meal_name": "Omelette", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://joyfoodsunshine.com/omelette-recipe/"},
    {"meal_type": "Breakfast", "meal_name": "Avocado Toast", "preparation_time": "Quick and Easy",
     "calories": "Low in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://cookieandkate.com/avocado-toast-recipe/"},
    {"meal_type": "Breakfast", "meal_name": "Greek Yogurt with Honey and Nuts", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://toriavey.com/yiaourti-me-meli-greek-yogurt-honey-and-nuts/"},
    {"meal_type": "Breakfast", "meal_name": "Smoothie Bowl", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://minimalistbaker.com/favorite-smoothie-bowl-5-minutes/"},
    {"meal_type": "Breakfast", "meal_name": "Overnight Oats", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://feelgoodfoodie.net/recipe/overnight-oats/"},
    {"meal_type": "Breakfast", "meal_name": "Pancakes", "preparation_time": "Moderate", "calories": "High in Calories",
     "ingredients": "Rich in carbs",
     "recipe_link": "https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/"},
    {"meal_type": "Breakfast", "meal_name": "Beef Samosas", "preparation_time": "Extended",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.allrecipes.com/recipe/24871/beef-samosas/"},
    {"meal_type": "Breakfast", "meal_name": "French Toast", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://tastesbetterfromscratch.com/classic-french-toast/"},
    {"meal_type": "Breakfast", "meal_name": "Eggs Benedict", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.recipetineats.com/eggs-benedict/"},
    {"meal_type": "Breakfast", "meal_name": "Chocolate Mug Cake", "preparation_time": "Moderate",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.allrecipes.com/recipe/241038/microwave-chocolate-mug-cake/"},
    {"meal_type": "Breakfast", "meal_name": "Veggie Frittata", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://www.themediterraneandish.com/vegetable-frittata/"},
    {"meal_type": "Breakfast", "meal_name": "Kenyan Mandazi with Tea", "preparation_time": "Moderate",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://swahilifood.com/how-to-make-soft-mandazi-biegnets/"},
    {"meal_type": "Breakfast", "meal_name": "Chia Pudding", "preparation_time": "Quick and Easy",
     "calories": "Low in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.loveandlemons.com/chia-seed-pudding/"},
    {"meal_type": "Breakfast", "meal_name": "Breakfast Burrito", "preparation_time": "Moderate",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.loveandlemons.com/breakfast-burrito/"},
    {"meal_type": "Breakfast", "meal_name": "Cottage Cheese Pancakes", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://momsdish.com/recipe/177/cottage-cheese-pancakes"},

    # Lunch
    {"meal_type": "Lunch", "meal_name": "Ndengu and Rice", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in protein",
     "recipe_link": "https://toasterding.com/basic-rice-ndengu-stew-recipe/"},
    {"meal_type": "Lunch", "meal_name": "Matoke", "preparation_time": "Moderate", "calories": "High in Calories",
     "ingredients": "Rich in carbs", "recipe_link": "https://cheflolaskitchen.com/matoke/"},
    {"meal_type": "Lunch", "meal_name": "Ugali and Fish", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.pikachakula.com/recipe-view/fried-fish-tomato-gravy-ugali/"},
    {"meal_type": "Lunch", "meal_name": "Ugali and Chicken", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://pendolamama.co.ke/basic-chicken-stew/"},
    {"meal_type": "Lunch", "meal_name": "Grilled Chicken Salad", "preparation_time": "Quick and Easy",
     "calories": "Low in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.dinneratthezoo.com/grilled-chicken-salad/"},
    {"meal_type": "Lunch", "meal_name": "Quinoa Bowl", "preparation_time": "Moderate", "calories": "Medium in Calories",
     "ingredients": "Rich in carbs", "recipe_link": "https://greenhealthycooking.com/chicken-quinoa-bowl/"},
    {"meal_type": "Lunch", "meal_name": "Turkey Sandwich", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.favfamilyrecipes.com/turkey-sandwich/"},
    {"meal_type": "Lunch", "meal_name": "Vegetable Stir-Fry", "preparation_time": "Quick and Easy",
     "calories": "Low in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://therecipecritic.com/vegetable-stir-fry/"},
    {"meal_type": "Lunch", "meal_name": "Green Peas and Rice", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://cookpad.com/ke/recipes/3034719-peas-stew-and-rice"},
    {"meal_type": "Lunch", "meal_name": "Stuffed Bell Peppers", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://www.budgetbytes.com/stuffed-bell-peppers/"},
    {"meal_type": "Lunch", "meal_name": "Tuna Salad", "preparation_time": "Quick and Easy",
     "calories": "Low in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.delish.com/cooking/recipe-ideas/a43533456/tuna-salad-recipe/"},
    {"meal_type": "Lunch", "meal_name": "Kenyan Pilau", "preparation_time": "Extended",
     "calories": "Medium in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://cheflolaskitchen.com/east-african-pilau/"},
    {"meal_type": "Lunch", "meal_name": " Sukuma Wiki with Ugali", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://www.africanbites.com/sukuma-wiki/"},
    {"meal_type": "Lunch", "meal_name": "Chicken Caesar Wrap", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.tasteandtellblog.com/chicken-caesar-wraps/"},
    {"meal_type": "Lunch", "meal_name": "Mushroom Risotto", "preparation_time": "Extended",
     "calories": "Medium in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.loveandlemons.com/mushroom-risotto/"},
    {"meal_type": "Lunch", "meal_name": "Githeri", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://cookpad.com/ke/recipes/2353615-tasty-githeri"},


    # Supper
    {"meal_type": "Supper", "meal_name": "Beef Stew and Rice", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://shewearsmanyhats.com/easy-stew-beef-rice-recipe/"},
    {"meal_type": "Supper", "meal_name": "Fish Curry", "preparation_time": "Extended", "calories": "Medium in Calories",
     "ingredients": "Rich in lean proteins", "recipe_link": "https://greenspoon.co.ke/swahili-fish-curry/"},
    {"meal_type": "Supper", "meal_name": "Kuku Paka (Chicken in Coconut Sauce)", "preparation_time": "Moderate",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.recipetineats.com/african-chicken-curry-kuku-paka/"},
    {"meal_type": "Supper", "meal_name": "Chapati and Beef", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://cookpad.com/ke/recipes/11254504-chapati-with-beef-stew"},
    {"meal_type": "Supper", "meal_name": "Rice and Beans", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in proteins",
     "recipe_link": "https://spainonafork.com/3-bean-stew-with-rice-vegetables-recipe/"},
    {"meal_type": "Supper", "meal_name": "Mukimo and Beef", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://cookpad.com/ke/recipes/2747990-mukimo-beef-stew-and-mixed-vegetables"},
    {"meal_type": "Supper", "meal_name": "Pilau", "preparation_time": "Extended", "calories": "Medium in Calories",
     "ingredients": "Rich in carbs", "recipe_link": "https://cheflolaskitchen.com/east-african-pilau/"},
    {"meal_type": "Supper", "meal_name": "Spaghetti Bolognese", "preparation_time": "Moderate",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.recipetineats.com/spaghetti-bolognese/"},
    {"meal_type": "Supper", "meal_name": "Chicken Stir-Fry", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.budgetbytes.com/chicken-stir-fry/"},
    {"meal_type": "Supper", "meal_name": "Vegetable Curry", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://www.cookwithmanali.com/mixed-veg-recipe/"},
    {"meal_type": "Supper", "meal_name": "Beef Tacos", "preparation_time": "Quick and Easy",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://feelgoodfoodie.net/recipe/ground-beef-tacos-napa-cabbage-guacamole/"},
    {"meal_type": "Supper", "meal_name": "Rice and Vegetable Stir-Fry", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://cookieandkate.com/vegetable-fried-rice-recipe/"},
    {"meal_type": "Supper", "meal_name": " Nyama Choma with Kachumbari", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://cookpad.com/ke/recipes/6358489-nyama-choma-with-traditional-vegetables-and-kachumbari"},
    {"meal_type": "Supper", "meal_name": "Stuffed Sweet Potatoes", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.loveandlemons.com/stuffed-sweet-potatoes/"},
    {"meal_type": "Supper", "meal_name": "Eggplant Parmesan", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.simplyrecipes.com/recipes/eggplant_parmesan/"},
    {"meal_type": "Supper", "meal_name": "Sweet and Sour Pork", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in proteins",
     "recipe_link": "https://www.recipetineats.com/sweet-and-sour-pork/"},
    {"meal_type": "Supper", "meal_name": "Chicken Fajitas", "preparation_time": "Quick and Easy",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.bbcgoodfood.com/recipes/collection/chicken-fajitas"},
    {"meal_type": "Supper", "meal_name": "Chili Con", "preparation_time": "Extended",
     "calories": "High in Calories", "ingredients": "Rich in carbs",
     "recipe_link": "https://www.cuisinefiend.com/802/chilli-con-corn"},
    {"meal_type": "Supper", "meal_name": "Baked Salmon with Vegetables", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in lean proteins",
     "recipe_link": "https://www.lecremedelacrumb.com/best-easy-healthy-baked-salmon/"},
    {"meal_type": "Supper", "meal_name": "Pasta Primavera", "preparation_time": "Moderate",
     "calories": "Medium in Calories", "ingredients": "Rich in vegetables",
     "recipe_link": "https://www.loveandlemons.com/pasta-primavera/"},
]

# Write to CSV file
with open('meal_plan.csv', 'w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["meal_type", "meal_name", "preparation_time", "calories", "ingredients", "recipe_link"])
    writer.writeheader()
    writer.writerows(meals)

print("CSV file 'meal_plan.csv' has been created.")